matrix:
- name: Markdown
  sources:
  - '!venv/**/*.md|**/*.md'
  default_encoding: utf-8
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - .github/config/.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre