#cloud-config
runcmd:
  - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elastic-keyring.gpg
  - sudo apt-get install apt-transport-https
  - echo "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
  - apt-get update && apt-get install logstash
  - /usr/share/logstash/bin/logstash-plugin install logstash-input-azure_event_hubs
  - /usr/share/logstash/bin/logstash-plugin install microsoft-sentinel-logstash-output-plugin
  - mkdir /usr/share/logstash/config
  - mkdir /etc/sysconfig
  - echo LOGSTASH_KEYSTORE_PASS=${logstashKeyStorePassword} > /etc/sysconfig/logstash
  - chmod 600 /etc/sysconfig/logstash 
  - export LOGSTASH_KEYSTORE_PASS=${logstashKeyStorePassword}
  - /usr/share/logstash/bin/logstash-keystore create --path.settings /etc/logstash
  - echo "${eventHubConnectionString}" | /usr/share/logstash/bin/logstash-keystore add eventhubconnectionstring --path.settings /etc/logstash
  - echo "${eventHubConsumerGroupName}" | /usr/share/logstash/bin/logstash-keystore add eventhubconsumergroupname --path.settings /etc/logstash
  - echo "${eventHubInputStorageAccountConnectionString}" | /usr/share/logstash/bin/logstash-keystore add eventhubinputstorageaccountconnectionstring --path.settings /etc/logstash
  - echo "${lawPluginAppId}" | /usr/share/logstash/bin/logstash-keystore add lawpluginappid --path.settings /etc/logstash
  - echo "${lawPluginAppSecret}" | /usr/share/logstash/bin/logstash-keystore add lawpluginappsecret --path.settings /etc/logstash
  - echo "${lawPluginTenantId}" | /usr/share/logstash/bin/logstash-keystore add lawplugintenantid --path.settings /etc/logstash
  - echo "${lawPluginDataCollectionEndpointURI}" | /usr/share/logstash/bin/logstash-keystore add lawplugindatacollectionendpointuri --path.settings /etc/logstash
  - echo "${lawPluginDcrImmutableId}" | /usr/share/logstash/bin/logstash-keystore add lawplugindcrimmutableid --path.settings /etc/logstash
  - echo "${lawPluginDcrStreamName}" | /usr/share/logstash/bin/logstash-keystore add lawplugindcrstreamname --path.settings /etc/logstash
  - curl -L https://raw.githubusercontent.com/jchancellor-ms/avs-terraform/main/modules/avs_log_filtering_vm/templates/logstash-avs-custom.conf > /etc/logstash/conf.d/logstash-avs-custom.conf
  - |
    sed -i -e "s/# pipeline.ecs_compatibility: v8/pipeline.ecs_compatibility: disabled/g" /etc/logstash/logstash.yml
  - chmod 644 /etc/logstash/startup.options
  - |
    chown -R logstash:logstash /var/log/logstash
  - chmod -R 755 /var/log/logstash
  - systemctl enable logstash.service
  - systemctl start logstash.service