name: ARM Build Action
on: push

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: ARM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Run Build-ARM.ps1
      uses: azure/powershell@53dd145408794f7e80f97cfcca04155c85234709 # v2.0.0
      with:
        inlineScript: |
          ./Build-ARM.ps1
          $changes = git status --porcelain
          if ($changes) {
            Write-Host $changes
            Write-Error "ARM templates are out of date!" -ErrorAction stop
          }
          Write-Host "ARM templates are up to date."
        azPSVersion: "latest"
