name: ARM Build Action
on: push

jobs:
  build:
    name: ARM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Run Build-ARM.ps1
      uses: azure/powershell@53dd145408794f7e80f97cfcca04155c85234709 # v2.0.0
      with:
        inlineScript: |
          ./Build-ARM.ps1
          $changes = git status --porcelain
          if ($changes) {
            Write-Host $changes
            Write-Error "ARM templates are out of date!" -ErrorAction stop
          }
          Write-Host "ARM templates are up to date."
        azPSVersion: "latest"
