---
    name: Code Review
    
    on:
      pull_request:
        branches:
          - main
      workflow_dispatch: {}
    
    # Declare default permissions as read only.
    permissions: read-all
    
    jobs:
      super-linter:
        name: GitHub Super Linter
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            with:
              fetch-depth: 0
    
          - name: Lint AVS-Landing-Zone directory
            uses: docker://github/super-linter:v4.9.5@sha256:f8464fa5488596e8c996cbef5b80f1c6ff069b2eb7bc13befcdcf9bd1251ad5e
            env:
              # Only lint changed files
              VALIDATE_ALL_CODEBASE: false
              # Need to define main branch as default
              # is set to master in super-linter
              DEFAULT_BRANCH: main
              # Enable setting the status of each individual linter
              # run in the Checks section of a pull request
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # Only the following files will be linted:
              FILTER_REGEX_INCLUDE: .*AVS-Landing-Zone\/.*
              # The following linter types will be enabled:
              VALIDATE_ARM: true
              VALIDATE_JSON: true
              VALIDATE_TERRAFORM_FMT: true
              VALIDATE_MARKDOWN: true
              VALIDATE_POWERSHELL: true
              # Additional settings:
              # Disable errors to only generate a report
              DISABLE_ERRORS: true
              ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
    
          - name: Lint Brownfield directory
            uses: docker://github/super-linter:v4.9.5@sha256:f8464fa5488596e8c996cbef5b80f1c6ff069b2eb7bc13befcdcf9bd1251ad5e
            env:
              # Only lint changed files
              VALIDATE_ALL_CODEBASE: false
              # Need to define main branch as default
              # is set to master in super-linter
              DEFAULT_BRANCH: main
              # Enable setting the status of each individual linter
              # run in the Checks section of a pull request
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # Only the following files will be linted:
              FILTER_REGEX_INCLUDE: .*Brownfield\/.*
              # The following linter types will be enabled:
              VALIDATE_ARM: true
              VALIDATE_JSON: true
              VALIDATE_TERRAFORM_FMT: true
              VALIDATE_MARKDOWN: true
              VALIDATE_POWERSHELL: true
              # Additional settings:
              # If a shell script is not executable, the bash-exec
              # linter will report an error when set to true
              DISABLE_ERRORS: true
              ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true

          - name: Lint hcx directory
            uses: docker://github/super-linter:v4.9.5@sha256:f8464fa5488596e8c996cbef5b80f1c6ff069b2eb7bc13befcdcf9bd1251ad5e
            env:
              # Only lint changed files
              VALIDATE_ALL_CODEBASE: false
              # Need to define main branch as default
              # is set to master in super-linter
              DEFAULT_BRANCH: main
              # Enable setting the status of each individual linter
              # run in the Checks section of a pull request
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # Only the following files will be linted:
              FILTER_REGEX_INCLUDE: .*hcx\/.*
              # The following linter types will be enabled:
              VALIDATE_ARM: true
              VALIDATE_JSON: true
              VALIDATE_TERRAFORM_FMT: true
              VALIDATE_MARKDOWN: true
              VALIDATE_POWERSHELL: true
              # Additional settings:
              # If a shell script is not executable, the bash-exec
              # linter will report an error when set to true
              DISABLE_ERRORS: true
              ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true

          - name: Lint Network Design Guide directory
            uses: docker://github/super-linter:v4.9.5@sha256:f8464fa5488596e8c996cbef5b80f1c6ff069b2eb7bc13befcdcf9bd1251ad5e
            env:
              # Only lint changed files
              VALIDATE_ALL_CODEBASE: false
              # Need to define main branch as default
              # is set to master in super-linter
              DEFAULT_BRANCH: main
              # Enable setting the status of each individual linter
              # run in the Checks section of a pull request
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # Only the following files will be linted:
              FILTER_REGEX_INCLUDE: .*Network Design Guide\/.*
              # The following linter types will be enabled:
              VALIDATE_ARM: true
              VALIDATE_JSON: true
              VALIDATE_TERRAFORM_FMT: true
              VALIDATE_MARKDOWN: true
              VALIDATE_POWERSHELL: true
              # Additional settings:
              # If a shell script is not executable, the bash-exec
              # linter will report an error when set to true
              DISABLE_ERRORS: true
              ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true

          - name: Lint terraform directory
            uses: docker://github/super-linter:v4.9.5@sha256:f8464fa5488596e8c996cbef5b80f1c6ff069b2eb7bc13befcdcf9bd1251ad5e
            env:
              # Only lint changed files
              VALIDATE_ALL_CODEBASE: false
              # Need to define main branch as default
              # is set to master in super-linter
              DEFAULT_BRANCH: main
              # Enable setting the status of each individual linter
              # run in the Checks section of a pull request
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # Only the following files will be linted:
              FILTER_REGEX_INCLUDE: .*terraform\/.*
              # The following linter types will be enabled:
              VALIDATE_ARM: true
              VALIDATE_JSON: true
              VALIDATE_TERRAFORM_FMT: true
              VALIDATE_MARKDOWN: true
              VALIDATE_POWERSHELL: true
              # Additional settings:
              # If a shell script is not executable, the bash-exec
              # linter will report an error when set to true
              DISABLE_ERRORS: true
              ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true